set autoindent

set number

set expandtab

syntax enable           " enable syntax processing

set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing

set cursorline          " highlight current line
set number              " show line numbers
set mouse=a             " enable mouse support (might not work well on Mac OS X)set wrap                " wrap lines
set encoding=utf-8      " set encoding to UTF-8 (default was "latin1")

