---

- name: "Download oh-my-tmux"
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: ~/.tmux
  
- name: "Create Link"
  file:
    src: /home/oparkins/.tmux/.tmux.conf
    dest: /home/oparkins/.tmux.conf
    state: link

- name: "Copy Local File"
  copy:
    src: /home/oparkins/.tmux/.tmux.conf.local
    dest: /home/oparkins/.tmux.conf.local
    remote_src: yes